<?php

namespace App\Command;

use App\Entity\Forename;
use App\Repository\ForenameRepository;
use App\Service\SlugGenerator;
use BorderCloud\SPARQL\SparqlClient;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class WikidataDownloadForenameCommand extends WikidataDownloadCommand
{
    protected static $defaultName = 'app:wikidata-download-forename';

    protected function getQuery($offset, $offsetStep) {
        $query = "SELECT ?forename ?forenameLabel
            WHERE
            {
                ?forename wdt:P31/wdt:P279* wd:Q202444.
                SERVICE wikibase:label { bd:serviceParam wikibase:language 'fr,en,de,es'. }
            }
            LIMIT $offsetStep
            OFFSET $offset
            ";
        return $query;
    }

    protected function getObjectFromSparqlRow($row) {
        $forename = new Forename();
        $forename->setLabel($row["forenameLabel"]);
        $forename->setQ(str_replace("http://www.wikidata.org/entity/", "", $row["forename"]));
        $forename->setLabels($this->slugGenerator->clean($forename->getLabel()));

        if ($forename->getLabels() != "") {
            return $forename;
        }
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
